### ISSUE TITLE
Code for dreamerv2 baseline doesn't work

### ISSUE THREAD

**Issue by zhixuan-lin** [danijar/crafter-baselines#2]
Hello,

First thanks for making this awesome lightweight environment! I'm trying to run the dreamerv2 baseline in this repo but the code doesn't work. Clearly, it is because `dv2.configs` is a `dict` so `dv2.configs.crafter` would cause error.

When I looked at the dreamerv2 code and tried to fix it, I got a bit confused about how configurations are handled (e.g.,  there is a `crafter` entry in `configs.yaml` but the `--configs` flag doesn't seem to do anything...). Also, I saw your [reply to an issue](https://github.com/danijar/crafter/issues/1#issuecomment-887138898) that indicates the right hyperparameters for Crafter, but these are not present in this repo (i.e. [main.py](https://github.com/danijar/crafter-baselines/blob/bea8cc3ba7f1140e7ca1550cd702cbf2ec656065/dreamerv2/main.py)), nor in the dreamerv2 repo.

So I wonder if you can point out what's the exact way to reproduce the dreamerv2 results on crafter with the right hyperparameters? It would be even better if you could just provide a runnable version in this baseline repo. Many thanks!

**Comment by danijar** [comment]
Thanks, fixed!
